name: campus_agent
description: A specialized agent for handling campus-related queries with structured responses
version: 1.0.0

tools:
  - name: search_tool
    type: web_search
    config:
      max_results: 3
      trusted_domains:
        - reva.edu.in
        - education.gov.in
        
  - name: web_fetcher_tool
    type: web_fetcher
    config:
      max_retries: 3
      timeout: 10

data_sources:
  - name: campus_data
    type: json
    path: data/college.json
    required: true

response_format:
  section_separator: "="
  subsection_separator: "-"
  bullet_point: "•"
  line_spacing: 1
  
keywords:
  overview:
    - about
    - overview
    - tell me about
    - what is
    - university details
    
  academics:
    - courses
    - programs
    - academics
    - departments
    - study
    
  placements:
    - placement
    - package
    - job
    - recruitment
    - companies
    
  facilities:
    - facilities
    - hostel
    - accommodation
    - amenities
    - infrastructure
    
  campus_life:
    - life
    - activities
    - clubs
    - events
    - fest
    
  admissions:
    - admission
    - apply
    - entrance
    - exam
    - fee
    - scholarship
    
  contact:
    - contact
    - address
    - location
    - reach
    - phone
    - email 